stages:
  - release

bump_changelog:
  stage: release
  script:
    - .gitlab/scripts/bump_changelog.sh
    - git config user.email "ci@example.com"
    - git config user.name "CI Bot"
    - git add CHANGELOG.md
    - git commit -m "chore: bump changelog version"
    - git push origin "$CI_COMMIT_REF_NAME"
  only:
    - main
