from typing import Iterable, Tuple, Dict, Union
from pathlib import Path

import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt
from matplotlib.axes import Axes
import re
import h5py

from .math_funcs import *

def _get_lumer_datafile_dims(file_path: Path):
    dims = []
    regex = re.compile(r'u[xy]\((\d+),')
    with open(file_path, 'r', encoding='utf-8') as file:
        for line in file:
            if match:=regex.search(line):
                dims.append(int(match.group(1)))
    return dims

def _load_txt_file(file_path: Path):
    '''
    Loads Lumerical mode far field projection data exported in text standard format.
    '''
    def cast_complex(s):
        # Remove parentheses and split by comma
        s = s.strip('()')
        real, imag = map(float, s.split(','))
        return real + 1j * imag

    nx, ny = _get_lumer_datafile_dims(file_path)

    ux = np.rad2deg(np.arcsin(np.linspace(-1, 1, nx)))
    uy = ux.copy() if nx==ny else np.rad2deg(np.arcsin(np.linspace(-1, 1, ny)))
    farfield_data = np.loadtxt(
        file_path,
        converters=dict().fromkeys(range(ny), cast_complex),
        dtype=np.complex128,
        skiprows=nx+ny+3
    )
    
    return ux, uy, farfield_data.T
    

def _load_mat_file(file_path: Path):
    '''
    Loads Lumerical mode far field projection data exported in matlab .mat format.
    '''
    with h5py.File(file_path) as f:
        ux = np.rad2deg(np.arcsin(f['ux'][:])).squeeze() # type: ignore
        uy = np.rad2deg(np.arcsin(f['uy'][:])).squeeze() # type: ignore
        key = [s for s in str(f.keys()).split("'") if s.startswith('farfield')][0]
        farfield_data = f[key][:]['real'].squeeze() + 1j*f[key][:]['imag'].squeeze() # type:ignore
    
    return ux, uy, farfield_data

def load_data(file_path: Path):
    """
    Loads data (ux, uy, farfield_data) from a file.

    Args:
        file_path_str (str): The path to the file.

    Returns:
        tuple: A tuple containing (ux, uy, farfield_data) as NumPy arrays.

    Raises:
        ValueError: If the file extension is not supported.
        FileNotFoundError: If the file does not exist.
        IOError: For other issues during file loading (e.g., parsing errors).
    """
    if not file_path.exists():
        raise FileNotFoundError(f"Error: The file at '{file_path}' was not found.")
    
    supported_loaders = {
        '.txt': _load_txt_file,
        '.mat': _load_mat_file
    }

    if file_path.suffix not in supported_loaders:
        supported_exts_str = ', '.join(supported_loaders.keys())
        raise ValueError(
            f"Unsupported file extension: '{file_path.suffix}'. "
            f"Supported extensions are: {supported_exts_str}"
        )
    
    loader_function = supported_loaders[file_path.suffix]
    try:
        ux, uy, farfield_data = loader_function(file_path)
        return ux, uy, farfield_data
    except Exception as e:
        # Catch any unexpected errors from the loader and re-raise as IOError
        raise IOError(f"An error occurred while loading '{file_path}': {e}") from e

def cartesian2polar(x, y):
    '''
    Translates data in cartesian coordinates to polar coordinates.
    '''
    xx, yy = np.meshgrid(x, y)
    r = np.sqrt(xx**2 + yy**2)
    theta = np.arctan2(yy, xx)

    return r, theta

def load_mode_farfield_projection_data(file_path: Union[Path, str]):
    '''
    Loads farfield projection data file generated by Ansys Lumerical MODE eigensolver
    in the text (standard) or .mat format.
    
    Returns
    --------
    (theta, r): tuple[np.ndarray, np.ndarray]
        Polar coordinates of the loaded data points
    farfield_data: np.ndarray
        Numpy array with farfield projection data
    '''
    file_path = Path(file_path)
    ux, uy, farfield_data = load_data(file_path)
    r, theta = cartesian2polar(ux, uy)

    return r, theta, farfield_data

def fit_gaussian(x_data, y_data, **kwargs):
    A_guess = y_data.max()
    x0_guess = x_data[y_data.argmax()]
    sigma_guess = (x_data[-1] - x_data[0]) / 4

    p0 = kwargs.get('p0') or [A_guess, x0_guess, sigma_guess]

    popt, _ = curve_fit(gaussian, x_data, y_data, p0)
    return popt

def aperture(x_data: Iterable, y_data: Iterable, threshold: Union[str, float]='esqr') -> Dict:
    '''
    thershold: str or float
        Threshold value used to calculate parameters. Use "e" for 1/e factor,
        "esqr" for 1/e^2 factor or float in range (0, 1).
     '''
    A_fit, x0_fit, sigma_fit = fit_gaussian(x_data, y_data)

    if isinstance(threshold, str) and threshold in ('e', 'esqr'):
        delta_x = np.sqrt(2) * sigma_fit if threshold=='e' else 2 * sigma_fit
    elif isinstance(threshold, float) and threshold > 0 and threshold < 1:
        delta_x = sigma_fit * np.sqrt(2*np.log(1/threshold))
    else:
        raise ValueError(f'Wrong value of thershold! (look at docstring)')

    x_left = x0_fit - delta_x
    x_right = x0_fit + delta_x

    return {
        'fit_params': {'A': A_fit, 'x0': x0_fit, 'sigma': sigma_fit},
        'threshold_points': (x_left, x_right),
        'FWHM': 2 * np.sqrt(2 * np.log(2)) * sigma_fit,
    }

def plot_projection(theta, r, data, **kwargs) -> Axes:
    '''Plots farfield projection (absolute value of complex) in the polar coordinates.'''
    if 'marker' not in kwargs:
        kwargs['marker'] = '.'
    _, ax = plt.subplots(subplot_kw={"projection":"polar"})
    ax.scatter(theta, r, c=abs(data), **kwargs)
    return ax